### ISSUE TITLE
Container and service for the annotation pipeline

### ISSUE THREAD

**Issue by epageperron** [cdli-gh/Framework#82]
_From @epageperron on March 4, 2018 0:50_

## Summary

@khoidt will be preparing a bash script to facilitate the work of annotators in the manipulation of the files and tools but we also need to integrate the tools as a service as part of the CDLI infrastructure for further work, after Framework and MTAAC. Editors shouldn't have to install tools, download files, process them and re-upload, although of course the tools should remain available here on Github and usable completely disconnected from CDLI by anyone who would want to.

We have a Python container planned which uses the /tools/ "app" folder in the Framework Gitlab repo 

https://gitlab.com/cdli/framework/tree/phoenix/develop/app/tools/

But because of the click (http://click.pocoo.org/5/) maybe we can install the tools while deploying the container itself, I'm not sure what is best practice here (@nomoon ?).

Cake/Shell should be able to communicate with the Python container and run the tools and process files. 

#### 📈 Progress (0-1): 

See Gantt: http://cdli-dev.org/gantt/mtaac_work/

_Copied from original issue: cdli-gh/mtaac_work#46_

**Comment by epageperron** [comment]
_From @jayanthjaiswal on April 10, 2018 1:15_

@epageperron  Do you mean [this](https://spin.atomicobject.com/2015/11/30/command-line-tools-docker/) ?


The biggest downside of this approach is that it requires users to first have Docker installed. Depending on your application, however, having a single dependency on Docker may be much simpler to support.

**Comment by epageperron** [comment]
I'll edit the issue to add details and make it more clear

**Comment by epageperron** [comment]
Done.

**Comment by nomoon** [comment]
A few thoughts:

If your Python scripts contain a number of dependencies (i.e. Click, Docopts, etc.) it's best to install those when you build the container. You can take examples from the [current container dockerfiles and build scripts](https://gitlab.com/cdli/deploy/tree/develop/docker), but it should be as straightforward as adding a "pip install [dependency]" command to the process.

You say above "Cake/Shell should be able to communicate with the Python container and run the tools and process files", which requires some clarification. Since the Cake container is basically its own VM and the Tools container would be as well, they can share files (through data volumes and mounts) and communicate over the internal Docker network. However, there's no way for the Cake container to simply execute a program on the Tools container. Every process on each container must either be started from inside (on boot or through the running software starting new software) or by an administrator-level `docker exec` command (which we cannot permit the docker services themselves calling, since it is a complete security failure).

This all suggests that the Tools container needs to expose some sort of API/daemon on the internal network that can receive requests to run its scripts.

**Comment by epageperron** [comment]
Makes sense ! Thanks for the insight

**Comment by epageperron** [comment]
https://gitlab.com/cdli/framework/issues/79
